services:
  bot:
    container_name: "eva-bot"
    build:
      context: .
    working_dir: "/app"
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python -m eva"
    ports:
      - "8080:8080"
  redis:
    container_name: "eva-redis"
    image: redis:7.0-rc-alpine
    hostname: redis
    volumes:
        - "./redis.conf:/usr/local/etc/redis/redis.conf"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    restart: "unless-stopped"
  worker:
    container_name: "eva-worker"
    build:
      context: .
    working_dir: "/app"
    volumes:
      - .:/app
    command: "python -m worker"
    restart: unless-stopped
